server:
  port: 8080
spring:
  application:
    name: "movieService"
  devtools:
    add-properties: false
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: marviniscool
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
cors:
  allowed-origins: "*"
security:
  jwt:
    secret-key: Y0x0RjJYajZTUWlRanF6Z2NaeDk4SUhUdGpQejlnTVI=
    expiration: 86400000
    refresh-token:
      expiration: 604800000
